### ISSUE TITLE
nodemailer error

### ISSUE THREAD

**Issue by sharax99** [UncleMle/PMRP-RageMP-GameMode#3]
i cant fix this error and i didnt receive email

![image](https://github.com/UncleMle/PMRP-RageMP-GameMode/assets/68154484/78b0707f-5354-4b31-8d79-064fc1ac2c7d)

**Comment by UncleMle** [comment]
This error is related to your configuration of the mail server credentials. Ensure to follow the tutorial provided https://www.youtube.com/watch?v=yuOK6D7deTo.

Marked as resolved.
