### ISSUE TITLE
Nodemailer error

### ISSUE THREAD

**Issue by dudulitrin** [UncleMle/PMRP-RageMP-GameMode#6]
i did the tutorial i create tha app password and i replace it in coreAPI.js
it look like this "
```const email = "dudu****@gmail.com";
const emailPassword = "xxxx yyyy zzzz www";
```
but when i try to register it didnt send me OTP and after 5 seconds server crash.
Can you help me?
![image](https://github.com/UncleMle/PMRP-RageMP-GameMode/assets/23567152/b49eb90b-f250-4f8a-b836-e08e707cb8dd)

**Comment by dudulitrin** [comment]
i also make tests and it works
![image](https://github.com/UncleMle/PMRP-RageMP-GameMode/assets/23567152/3ec44a76-c0e8-4ce2-b714-0704e963f19c)

**Comment by UncleMle** [comment]
Hi, this error shows there is a process running using the port needed for node mailer. You can either find and end the process manually or edit the port used in coreApi.js line 4.

**Comment by dudulitrin** [comment]
i try on diffrent ports and same think, it try to send first email and i guess it stuck somewhere and for second OTP crash cuz first one is deadlock somewhere... this is my theory but question is why it happend
port: 4122

![image](https://github.com/UncleMle/PMRP-RageMP-GameMode/assets/23567152/33e340f7-c8c1-4bcb-babb-9df836d4627b)

**Comment by dudulitrin** [comment]
port 5255
![image](https://github.com/UncleMle/PMRP-RageMP-GameMode/assets/23567152/05f5cde2-3a9d-47e2-8c6d-f874b9f12eed)

**Comment by dudulitrin** [comment]
do you think i need try debian? maybe same changes? I use ubuntu 20.04 on this VPS

**Comment by UncleMle** [comment]
Was an issue with VPS. Marked as resolved
